image: registry.labs.nic.cz/turris/foris-ci/python3

stages:
  - test

.base_image: &py3_common
  stage: test
  before_script:
    - pip install wheel
    - pip install virtualenv
    - virtualenv -p "$(which python)" /tmp/test
    - source /tmp/test/bin/activate
    - pip install .

test_python3:
  <<: *py3_common
  script:
    - python setup.py test --addopts="--backend openwrt --backend mock"

flake8:
  <<: *py3_common
  script:
    - python setup.py flake8
